Fix implicit declaration warning for time function
This warning would show up when compiling:

Maelstrom-netd.c:93:15: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
   93 |         now = time(NULL);

that was because the time function is actually declared in time.h
instead of sys/time.h, so include the former instead.